# Generated by Django 3.2.8 on 2021-11-13 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0003_alter_myuser_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Stationery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stationery.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.SmallIntegerField(choices=[(1, 'Quy 1'), (2, 'Quy 2'), (3, 'Quy 3'), (4, 'Quy 4')], null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'New'), (2, 'Approved'), (3, 'Rejected')], null=True)),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stationery.room')),
            ],
        ),
        migrations.CreateModel(
            name='Regist_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('registration_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stationery.registration')),
                ('stationery_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stationery.stationery')),
            ],
        ),
    ]
