# Generated by Django 3.2.8 on 2021-11-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0004_regist_detail_registration_stationery_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='regist_detail',
            old_name='registration_id',
            new_name='registration',
        ),
        migrations.RenameField(
            model_name='regist_detail',
            old_name='stationery_id',
            new_name='stationery',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='room_id',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='stationery',
            old_name='unit_id',
            new_name='unit',
        ),
    ]
