# Generated by Django 3.2.9 on 2021-11-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0005_auto_20211113_0443'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Registrations',
        ),
    ]
