# Generated by Django 3.2.9 on 2021-11-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0006_rename_registration_registrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='regist_detail',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
