# Generated by Django 3.2.9 on 2021-12-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0007_regist_detail_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regist_detail',
            name='total',
        ),
    ]
