# Generated by Django 3.2.9 on 2021-12-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0008_remove_regist_detail_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regist_detail',
            new_name='RegistDetail',
        ),
    ]
