# Generated by Django 3.2.9 on 2021-12-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0010_registrations_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Approved'), (3, 'Rejected')], default=1, null=True),
        ),
    ]
